////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

= Router Message Annotations

This document describes the implementation of the meta-data included
in messages passed between router nodes (interior and edge).

== Description

Each message passed between routers includes meta-data used to
communicate per-message state. This data is used by routers along the
forwarding path for various reasons.  Currently this information
includes:

* The identifier for the ingress interior router. This is the first
non-edge router the message encounters along the forwarding path.

* The trace list: an ordered list of router identifiers. This list
reflects the path the message has travelled in the router
network. Note that only routers of type 'interior' are included in
this list - edge routers are not included. The first entry on the list
is the ingress interior router.  The current router identifier is
added to the end of this list before the message is forwarded to a
next hop router.

* A destination address.  This optional field overrides the value of
the *to* field in the message properties section.

* A flag that indicates that the message is classified as
a *streaming message*. This provides a hint to the downstream router
to avoid unnecessary buffering of the message before forwarding it.

== Implementation Goals

The implementation should prioritize minimizing the overhead of parsing
and composing the per-message meta-data. This is necessary because
each router along the forwarding path needs to read, process and
update the meta data on the fly.

This implementation should also provide the means for extending or
modifying the meta-data definition in a backward compatible way.

== Versioning

The router will advertise the version of the meta data it supports to
its peer when the connection is established.  This is done by
including a version number in the properties field of the Open
performative. In the case where peers advertise different versions,
the numerically lower version will be used by both routers.

The open property map key for the version is
*"qd.annotations-version"*. The value is encoded as a signed
integer. This document defines version 2.

== Encoding

Router annotations will be encoded as a custom section in the
message. This section will appear as the first section of the message
(prior to the header section).

In order to avoid conflicts with the described types defined by the
AMQP specification, skupper-router will reserve a numeric domain
identifier.  The value for this domain will be *0x534B5052*. This is
the four ascii character sequence 'SKPR'.

The value for the new section identifier will be *0x2D2D5241*. This is
the four ascii character sequence '--RA'.

These values allows for easy identification of the router annotation
section in the protocol trace logs.  Simply search for the string
'SKPR--RA'.

The definition of this custom section follows:

 <type name="skupper-router-annotations" class="composite" source="list" provides="section">
    <descriptor name="skupper:router-annotations" code="0x534B5052:0x2D2D5241"/>
    <field name="flags" type="uint" default="0" mandatory="true"/>
    <field name="to-override" type="str32-utf8" mandatory="false"/>
    <field name="ingress-router" type="str8-utf8" mandatory="false"/>
    <field name="trace" type="list" mandatory="true"/>
 </type>

* The flags field is used for passing boolean flags.  The least
significant bit (bit 0; hex 0x01) is used for the streaming flag.  All
other bits are reserved and initialized to zero. An interior router
must ignore these unreserved flags and pass them to the next hop
without modifying them.

* Entries on the trace list are restricted to the *str8-utf8*
type. Note that the trace list will always be present however it may
be a null list (AMQP list0, code 0x45) when sent by an edge router
(see below).

== Section Inclusion/Removal

* By default the new router message annotation section MUST NOT be
  present in messages arriving from non-router endpoints. Such
  messages must be *REJECTED* by the router.  It should be possible to
  disable this rule for debug and testing purposes via configuration.

* The router message annotation MUST be removed when sending a message
  over a non-inter-router/edge connection. It should be possible to
  disable this rule for debug and testing purposes via configuration.

== Edge Router Annotations

An edge router will include a router annotations section in all
messages sent to an interior router. However the edge router will only
populate the flags and to-override entries.  The ingress-router field
MUST be set to the AMQP null value (code 0x40). The trace list must be
sent as an empty list.

Interior routers will include the full set of router annotations -
including the ingress-router and trace list fields - on messages sent
to an edge router. It is expected that the edge router can safely
ignore the ingress-router and trace field values in this case.

