#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#



== qdrouterd shutdown procedure


How does the router shut down when interrupted with ctrl-C ?


. main_process() +
  is in its call to qd_server_run()

.. qd_server_run() +
   has called thread_run() once for each worker thread,
   including itself as one of the worker threads.

... thread_run() +
    is in a loop processing batches of events, calling 
    handle() on each event.

.... handle() +
     receives a Proton event of type PN_PROACTOR_INTERRUPT.
     It calls pn_proactor_interrupt() to interrupt the next
     thread, and then returns 'false'.

... thread_run() receives false return from handle(), indicating
    that the thread is no longer running. It drops out of the 
    running loop. If there is a connection, it calls 
    qd_conn_event_batch_complete() with last arg false, indicating that 
    the connection has not closed. It then calls pn_proactor_done()
    and returns, to be joined by qd_server_run().

.... qd_conn_event_batch_complete() frees the connection's free_link_session_list,
     along with the pn_link and pn_session of every qd session on the list.
     Because the connection was not closed, it calls the writable_handler()
     one more time, then returns.


.. qd_server_run() +
   after joining and freeing all worker threads, logs Shut
   Down notice, and returns.

. main_process() +
  nulls out and dispatch pointer, and calls qd_dispatch_free().
  It then flushes any remaining content in stdout, disables its 
  SIGINT handler, and sends SIGINT 
  to itsel, terminating the qdrouterd process.

.. qd_dispatch_free() +
   calls qd_http_server_free(), qd_connection_manager_free(), qd_policy_free(), qd_router_free(), qd_container_free(), qd_server_free(), qd_log_finalize(), qd_alloc_finalize(), qd_python_finalize(). It sets the router ID and Area NULL, calls qd_iterator_finalize(), frees allocated fields in the qd_dispatch_t structure, and frees the structure.

... qd_http_server_free() +
    text

... qd_connection_manager_free() +
    text

... qd_policy_free() +
    text

... qd_router_free() +
    text

... qd_container_free() +
    text

... qd_server_free() +
    text

... qd_log_finalize() +
    text

... qd_alloc_finalize() +
    text

... qd_python_finalize() +
    text

... qd_iterator_finalize() +
    text

    



