////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// configuring-router.adoc

[id='configuring-logging-{context}']
= Configuring logging

{RouterName} contains internal logging modules that provide important information about each router. For each module, you can configure the logging level, the format of the log file, and the location to which the logs should be written.

// Logging modules
:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// configuring-logging.adoc

[id='logging-modules-{context}']
= Logging modules

{RouterName} logs are broken into different categories called _logging modules_. Each module provides important information about a particular aspect of {RouterName}.

`DEFAULT`::
The default module. This module applies defaults to all of the other logging modules.

`ROUTER`::
This module provides information and statistics about the local router. This includes how the router connects to other routers in the network, and information about the remote destinations that are directly reachable from the router (link routes, waypoints, autolinks, and so on).

`ROUTER_HELLO`::
This module provides information about the _Hello_ protocol used by interior routers to exchange Hello messages, which include information about the router's ID and a list of its reachable neighbors (the other routers with which this router has bidirectional connectivity).

`ROUTER_LS`::
This module provides information about link-state data between routers, including Router Advertisement (RA), Link State Request (LSR), and Link State Update (LSU) messages.
+
Periodically, each router sends an LSR to the other routers and receives an LSU with the requested information. Exchanging the above information, each router can compute the next hops in the topology, and the related costs.

`ROUTER_MA`::
This module provides information about the exchange of mobile address information between routers, including Mobile Address Request (MAR) and Mobile Address Update (MAU) messages exchanged between routers. You can use this log to monitor the state of mobile addresses attached to each router.

`MESSAGE`::
This module provides information about AMQP messages sent and received by the router, including information about the address, body, and link. You can use this log to find high-level information about messages on a particular router.

`SERVER`::
This module provides information about how the router is listening for and connecting to other containers in the network (such as clients, routers, and brokers). This information includes the state of AMQP messages sent and received by the broker (open, begin, attach, transfer, flow, and so on), and the related content of those messages.

`AGENT`::
This module provides information about configuration changes made to the router from either editing the router's configuration file or using `qdmanage`.

`CONTAINER`::
This module provides information about the nodes related to the router. This includes only the AMQP relay node.

`ERROR`::
This module provides detailed information about error conditions encountered during execution.

`POLICY`::
This module provides information about policies that have been configured for the router.

.Additional resources

* For examples of these logging modules, see xref:troubleshooting-using-logs-{context}[].

:leveloffset!:

// Configuring default logging
:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// configuring-logging.adoc

[id='configuring-default-logging-{context}']
= Configuring default logging

You can specify the types of events that should be logged, the format of the log entries, and where those entries should be sent.

.Procedure

. In the `{RouterConfigFile}` configuration file, add a `log` section to set the default logging properties:
+
--
This example configures all logging modules to log events starting at the `info` level:

[options="nowrap",subs="+quotes"]
----
log {
    module: DEFAULT
    enable: info+
    includeTimestamp: yes
}
----

`module`:: Specify `DEFAULT`.

`enable`:: The logging level. You can specify any of the following levels (from lowest to highest):
+
* `trace` - provides the most information, but significantly affects system performance
* `debug` - useful for debugging, but affects system performance
* `info` - provides general information without affecting system performance
* `notice` - provides general information, but is less verbose than `info`
* `warning` - provides information about issues you should be aware of, but which are not errors
* `error` - error conditions that you should address
* `critical` - critical system issues that you must address immediately

+
To specify multiple levels, use a comma-separated list. You can also use `+` to specify a level and all levels above it. For example, `trace,debug,warning+` enables trace, debug, warning, error, and critical levels. For default logging, you should typically use the `info+` or `notice+` level. These levels will provide general information, warnings, and errors for all modules without affecting the performance of {RouterName}.

`includeTimestamp`:: Set this to `yes` to include the timestamp in all logs.

For information about additional log attributes, see link:{qdrouterdConfManPageUrl}#_log[log] in the `qdrouterd.conf` man page.
--

. If you want to configure non-default logging for any of the logging modules, add an additional `log` section for each module that should not follow the default.
+
--
This example configures the `ROUTER` logging module to log `debug` events:
[options="nowrap",subs="+quotes"]
----
log {
    module: ROUTER
    enable: debug
    includeTimestamp: yes
}
----
--

.Additional resources

* For more information about viewing and using logs, see xref:troubleshooting-{context}[].

:leveloffset!:
