////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// book.adoc

[id='managing-router-{context}']
= Managing {RouterName}



// Monitoring using the web console
:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// book.adoc

[id='monitoring-using-web-console'-{context}']
= Monitoring using {ConsoleName}

{ConsoleName} is a web console for monitoring the status and performance of {RouterName} router networks.

//.Prerequisites
include::partial$fragment-console-prereq.adoc[]

:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// monitoring-using-web-console.adoc

[id='setting-up-access-web-console'-{context}']
= Setting up access to {ConsoleName}

Before you can access the web console, you must configure a `listener` to accept HTTP connections for the web console and serve the console files.

.Procedure

. On the router from which you want to access the web console, open the `{RouterConfigFile}` configuration file.

. Add a `listener` to serve the console.
+
--
This example creates a `listener` that clients can use to access the web console:

[options="nowrap",subs="+quotes"]
----
listener {
    host: 0.0.0.0
    port: 8672
    role: normal
    http: true
    httpRootDir: /usr/share/qpid-dispatch/console
}
----
`host`:: The IP address (IPv4 or IPv6) or hostname on which the router will listen.

`port`:: The port number or symbolic service name, defined in `/etc/services`, on which the router will listen.

`role`:: The role of the connection. Specify `normal` to indicate that this connection is used for client traffic.

`http`:: Set this attribute to `true` to specify that this `listener` should accept HTTP connections instead of plain AMQP connections.

`httpRootDir`:: Specify the absolute path to the directory that contains the web console HTML files. The default directory is the stand-alone console installation directory, usually `/usr/share/qpid-dispatch/console`.
--

. If you want to secure access to the console, secure the `listener`.
+
--
For more information, see xref:securing-incoming-client-connections-{context}[]. This example adds basic user name and password authentication using SASL PLAIN:

[options="nowrap",subs="+quotes"]
----
listener {
    host: 0.0.0.0
    port: 8672
    role: normal
    http: true
    httpRootDir: /usr/share/qpid-dispatch/console
    authenticatePeer: yes
    saslMechanisms: PLAIN
}
----
--

. If you want to set up access to the web console from any other router in the router network, repeat this procedure for each router.

:leveloffset!:

:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// monitoring-using-web-console.adoc

[id='accessing-web-console'-{context}']
= Accessing {ConsoleName}

You can access the web console from a web browser.

.Procedure

. In a web browser, navigate to the web console URL.
+
--
The web console URL is the _<host>_:__<port>__ from the `listener` that you created to serve the web console. For example: `localhost:8672`.

The {ConsoleName} opens. If you set up user name and password authentication, the *Connect* tab is displayed.
--

. If necessary, log in to the web console.
+
--
If you set up user name and password authentication, enter your user name and password to access the web console.

The syntax for the user name is <__user__>@<__domain__>. For example: `admin@my-domain`.
--

:leveloffset!:

:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// monitoring-using-web-console.adoc

[id='monitoring-router-network-web-console'-{context}']
= Monitoring the router network using {ConsoleName}

The web console provides several sections that you can use to monitor the router network.

[cols="25,75"]
|===
| This section... | Provides...

| Overview
a|
Aggregated information about the router network. This information includes the following:

* Dashboard (shows router network statistics)
* Routers
* Addresses
* Links
* Connections
* Logs

| Visualizations
a|
Graphical view of the router network. You can see the following types of visualizations:

`Topology`:: Topology of the router network, including routers, clients, and brokers. This visualization also shows how messages are flowing through the network.
`Message flow`:: A chord diagram showing the real-time message flow by address.

| Details
| Detailed configuration information about each AMQP management entity, for each router in the router network. You can view and change the configuration of any of the routers in the network.

|===

:leveloffset!:

:leveloffset!:

// Monitoring using qdstat
:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// managing-router.adoc

[id='monitoring-using-qdstat-{context}']
= Monitoring using `qdstat`

The `qdstat` tool is a command-line tool for monitoring the status and performance of {RouterName} router networks.

:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// monitoring-using-qdstat.adoc

[id='syntax-using-qdstat-{context}']
= Syntax for using `qdstat`

You can use `qdstat` with the following syntax:

[options="nowrap",subs="+quotes"]
----
$ qdstat __<option>__ [__<connection-options>__] [__<secure-connection-options>__]
----

This specifies:

* An _option_ for the type of information to view.
* One or more optional _connection options_ to specify a router for which to view the information.
+
If you do not specify a connection option, `qdstat` connects to the router listening on localhost and the default AMQP port (5672).
* The _secure connection options_ if the router for which you want to view information only accepts secure connections.

.Additional resources

* For more information about `qdstat`, see the {qdstatManPageLink}.

:leveloffset!:

:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// monitoring-using-qdstat.adoc

[id='commands-monitoring-router-network-{context}']
= Commands for monitoring the router network

You can use `qdstat` to view the status of routers on your router network. For example, you can view information about the attached links and configured addresses, available connections, and nodes in the router network.

[cols="50,50"]
|===
| To... | Use this command...

| Create a state dump containing all statistics for all routers

A state dump shows the current operational state of the router network.
a|
[options="nowrap"]
----
$ qdstat --all-routers --all-entities
----

If you run this command on an interior router, it displays the statistics for all interior routers. If you run the command on an edge router, it displays the statistics for only that edge router.

| Create a state dump containing a single statistic for all routers
a|
[options="nowrap",subs="+quotes"]
----
$ qdstat -l\|-a\|-c\|--autolinks\|--linkroutes\|-g\|-m --all-routers
----

If you run this command on an interior router, it displays the statistic for all interior routers. If you run the command on an edge router, it displays the statistic for only that edge router.

| Create a state dump containing all statistics for a single router
a|
[options="nowrap"]
----
$ qdstat --all-entities
----

This command shows the statistics for the local router only.

| View general statistics for a router
a|
[options="nowrap",subs="+quotes"]
----
$ qdstat -g [all-routers\|__<connection-options>__]
----

| View a list of connections to a router
a|
[options="nowrap",subs="+quotes"]
----
$ qdstat -c [all-routers\|__<connection-options>__]
----

| View the AMQP links attached to a router

You can view a list of AMQP links attached to the router from clients (sender/receiver), from or to other routers into the network, to other containers (for example, brokers), and from the tool itself.
a|
[options="nowrap",subs="+quotes"]
----
$ qdstat -l [all-routers\|__<connection-options>__]
----

| View known routers on the router network
a|
[options="nowrap",subs="+quotes"]
----
$ qdstat -n [all-routers\|__<connection-options>__]
----

| View the addresses known to a router
a|
[options="nowrap",subs="+quotes"]
----
$ qdstat -a [all-routers\|__<connection-options>__]
----

| View a router's autolinks
a|
[options="nowrap",subs="+quotes"]
----
$ qdstat --autolinks [all-routers\|__<connection-options>__]
----

| View the status of a router's link routes
a|
[options="nowrap",subs="+quotes"]
----
$ qdstat --linkroutes [all-routers\|__<connection-options>__]
----

| View a router's policy global settings and statistics
a|
[options="nowrap",subs="+quotes"]
----
$ qdstat --policy [all-routers\|__<connection-options>__]
----

| View a router's policy vhost settings
a|
[options="nowrap",subs="+quotes"]
----
$ qdstat --vhosts [all-routers\|__<connection-options>__]
----

| View a router's policy vhost statistics
a|
[options="nowrap",subs="+quotes"]
----
$ qdstat --vhoststats [all-routers\|__<connection-options>__]
----

| View a router's vhostgroup settings
a|
[options="nowrap",subs="+quotes"]
----
$ qdstat --vhostgroups [all-routers\|__<connection-options>__]
----

| View a router's memory consumption
a|
[options="nowrap",subs="+quotes"]
----
$ qdstat -m [all-routers\|__<connection-options>__]
----

|===

.Additional resources

* For more information about the fields displayed by each `qdstat` command, see the {qdstatManPageLink}.

:leveloffset!:

:leveloffset!:

// Managing routers
:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// managing-router.adoc

[id='managing-routers-{context}']
= Managing routers



:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

[id='starting-router-{context}']
= Starting a router

You use the `qdrouterd` command to start a router. You can start a router in the foreground, the background, or as a service.

.Procedure

* Do one of the following:
+
--
[cols="30,70"]
|===
| To... | Enter this command...

| Start the router in the foreground
a|
[source,bash,options="nowrap"]
----
$ qdrouterd
----

| Start the router in the background as a daemon
a|
[source,bash,options="nowrap"]
----
$ qdrouterd -d
----

| Start the router as a service
a|
include::partial$fragment-start-router-service-command.adoc[]

[NOTE]
====
If you start the router as a service, the `systemd` `LimitNOFILE` limit affects the number of connections that can be open for the router. If you reach the limit, the router is not able to accept any more connections, and an error message is logged indicating "Too many open files". To avoid reaching this limit, increase the `LimitNOFILE` value for the `systemd` process.

include::partial$fragment-systemd-limitnofile-fmi.adoc[]
====

|===
--

:leveloffset!:

:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// managing-router.adoc

[id='changing-router-configuration-{context}']
= Changing a router's configuration

You can make a permanent change to a router's configuration by editing the router's configuration file directly. You must restart the router for the changes to take effect, but the changes will be saved even if the router is stopped.

.Procedure

. Do one of the following:
+
--
** Edit the default configuration file (`{RouterConfigFile}`).
** Create a new configuration file.
--

. Start (or restart) the router.
+
--
For more information, see xref:starting-router-{context}[].

If you created a new configuration file, you must specify the path using the `--conf` parameter. For example, the following command starts the router with a non-default configuration file:

[options="nowrap",subs="+quotes"]
----
$ qdrouterd -d --conf /etc/qpid-dispatch/new-configuration-file.conf
----
--

:leveloffset!:

Unresolved directive in managing-routers.adoc - include::../../modules/user-guide/syntax-using-qdmanage.adoc[leveloffset=+1]

:leveloffset!:

// Troubleshooting
:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// managing-router.adoc

[id='troubleshooting-{context}']
= Troubleshooting {RouterName}

You can use the {RouterName} logs to diagnose and troubleshoot error and performance issues with the routers in your router network.

:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// troubleshooting.adoc

[id='viewing-log-entries-{context}']
= Viewing log entries

You may need to view log entries to diagnose errors, performance problems, and other important issues. A log entry consists of an optional timestamp, the logging module, the logging level, and the log message.

.Procedure

* Do one of the following:

** View log entries on the console.
+
By default, events are logged to the console, and you can view them there. However, if the `output` attribute is set for a particular logging module, then you can find those log entries in the specified location (`stderr`, `syslog`, or a file).

** Use the *`qdstat --log`* command to view recent log entries.
+
--
You can use the `--limit` parameter to limit the number of log entries that are displayed. For more information about `qdstat`, see {qdstatManPageLink}.

This example displays the last three log entries for `Router.A`:

[options="nowrap",subs="+quotes"]
----
$ qdstat --log --limit=3 -r ROUTER.A
Wed Jun  7 17:49:32 2019 ROUTER (none) Core action 'link_deliver'
Wed Jun  7 17:49:32 2019 ROUTER (none) Core action 'send_to'
Wed Jun  7 17:49:32 2019 SERVER (none) [2]:0 -> @flow(19) [next-incoming-id=1, incoming-window=61, next-outgoing-id=0, outgoing-window=2147483647, handle=0, delivery-count=1, link-credit=250, drain=false]
----
--

NOTE: `vhost` entries are only populated if `multiTenant` is set to `true` in the `{RouterConfigFile}` configuration file.

.Additional resources

* For more information about configuring logging modules, see xref:configuring-default-logging-{context}[].

:leveloffset!:

:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// troubleshooting.adoc

[id='troubleshooting-using-logs-{context}']
= Troubleshooting using logs

You can use {RouterName} log entries to help diagnose error and performance issues with the routers in your network.

.Troubleshooting connections and links
====
In this example, `ROUTER` logs show the lifecycle of a connection and a link that is associated with it.

[options="nowrap"]
----
2019-04-05 14:54:38.037248 -0400 ROUTER (info) [C1] Connection Opened: dir=in host=127.0.0.1:55440 vhost= encrypted=no auth=no user=anonymous container_id=95e55424-6c0a-4a5c-8848-65a3ea5cc25a props= // <1>
2019-04-05 14:54:38.038137 -0400 ROUTER (info) [C1][L6] Link attached: dir=in source={<none> expire:sess} target={$management expire:sess} // <2>
2019-04-05 14:54:38.041103 -0400 ROUTER (info) [C1][L6] Link lost: del=1 presett=0 psdrop=0 acc=1 rej=0 rel=0 mod=0 delay1=0 delay10=0 // <3>
2019-04-05 14:54:38.041154 -0400 ROUTER (info) [C1] Connection Closed // <4>
----
<1> The connection is opened. Each connection has a unique ID (`C1`). The log also shows some information about the connection.
<2> A link is attached over the connection. The link is identified with a unique ID (`L6`). The log also shows the direction of the link, and the source and target addresses.
<3> The link is detached. The log shows the link's terminal statistics.
<4> The connection is closed.

NOTE: If necessary, you can use `qdmanage` to enable protocol-level trace logging for a particular connection. You can use this to trace the AMQP frames. For example:

[options="nowrap"]
----
$ qdmanage update --type=connection --id=C1 enableProtocolTrace=true
----
====

.Troubleshooting the network topology
====
In this example, on `Router.A`, the `ROUTER_HELLO` logs show that it is connected to `Router.B`, and that `Router.B` is connected to `Router.A` and `Router.C`:

[options="nowrap"]
----
Tue Jun  7 13:50:21 2016 ROUTER_HELLO (trace) RCVD: HELLO(id=Router.B area=0 inst=1465307413 seen=['Router.A', 'Router.C']) // <1>
Tue Jun  7 13:50:21 2016 ROUTER_HELLO (trace) SENT: HELLO(id=Router.A area=0 inst=1465307416 seen=['Router.B']) // <2>
Tue Jun  7 13:50:22 2016 ROUTER_HELLO (trace) RCVD: HELLO(id=Router.B area=0 inst=1465307413 seen=['Router.A', 'Router.C'])
Tue Jun  7 13:50:22 2016 ROUTER_HELLO (trace) SENT: HELLO(id=Router.A area=0 inst=1465307416 seen=['Router.B'])
----
<1> `Router.A` received a Hello message from `Router.B`, which can see `Router.A` and `Router.C`.
<2> `Router.A` sent a Hello message to `Router.B`, which is the only router it can see.

On `Router.B`, the `ROUTER_HELLO` log shows the same router topology from a different perspective:

[options="nowrap"]
----
Tue Jun  7 13:50:18 2016 ROUTER_HELLO (trace) SENT: HELLO(id=Router.B area=0 inst=1465307413 seen=['Router.A', 'Router.C']) // <1>
Tue Jun  7 13:50:18 2016 ROUTER_HELLO (trace) RCVD: HELLO(id=Router.A area=0 inst=1465307416 seen=['Router.B']) // <2>
Tue Jun  7 13:50:19 2016 ROUTER_HELLO (trace) RCVD: HELLO(id=Router.C area=0 inst=1465307411 seen=['Router.B']) // <3>
----
<1> `Router.B` sent a Hello message to `Router.A` and `Router.C`.
<2> `Router.B` received a Hello message from `Router.A`, which can only see `Router.B`.
<3> `Router.B` received a Hello message from `Router.C`, which can only see `Router.B`.
====

.Tracing the link state between routers
====
Periodically, each router sends a Link State Request (LSR) to the other routers and receives a Link State Update (LSU) with the requested information. Exchanging the above information, each router can compute the next hops in the topology, and the related costs.

In this example, the `ROUTER_LS` logs show the RA, LSR, and LSU messages sent between three routers:

[options="nowrap"]
----
Tue Jun  7 14:10:02 2016 ROUTER_LS (trace) SENT: LSR(id=Router.A area=0) to: Router.C
Tue Jun  7 14:10:02 2016 ROUTER_LS (trace) SENT: LSR(id=Router.A area=0) to: Router.B
Tue Jun  7 14:10:02 2016 ROUTER_LS (trace) SENT: RA(id=Router.A area=0 inst=1465308600 ls_seq=1 mobile_seq=1) // <1>
Tue Jun  7 14:10:02 2016 ROUTER_LS (trace) RCVD: LSU(id=Router.B area=0 inst=1465308595 ls_seq=2 ls=LS(id=Router.B area=0 ls_seq=2 peers={'Router.A': 1L, 'Router.C': 1L})) // <2>
Tue Jun  7 14:10:02 2016 ROUTER_LS (trace) RCVD: LSR(id=Router.B area=0)
Tue Jun  7 14:10:02 2016 ROUTER_LS (trace) SENT: LSU(id=Router.A area=0 inst=1465308600 ls_seq=1 ls=LS(id=Router.A area=0 ls_seq=1 peers={'Router.B': 1}))
Tue Jun  7 14:10:02 2016 ROUTER_LS (trace) RCVD: RA(id=Router.C area=0 inst=1465308592 ls_seq=1 mobile_seq=0)
Tue Jun  7 14:10:02 2016 ROUTER_LS (trace) SENT: LSR(id=Router.A area=0) to: Router.C
Tue Jun  7 14:10:02 2016 ROUTER_LS (trace) RCVD: LSR(id=Router.C area=0) // <3>
Tue Jun  7 14:10:02 2016 ROUTER_LS (trace) SENT: LSU(id=Router.A area=0 inst=1465308600 ls_seq=1 ls=LS(id=Router.A area=0 ls_seq=1 peers={'Router.B': 1}))
Tue Jun  7 14:10:02 2016 ROUTER_LS (trace) RCVD: LSU(id=Router.C area=0 inst=1465308592 ls_seq=1 ls=LS(id=Router.C area=0 ls_seq=1 peers={'Router.B': 1L})) // <4>
Tue Jun  7 14:10:03 2016 ROUTER_LS (trace) Computed next hops: {'Router.C': 'Router.B', 'Router.B': 'Router.B'} // <5>
Tue Jun  7 14:10:03 2016 ROUTER_LS (trace) Computed costs: {'Router.C': 2L, 'Router.B': 1}
Tue Jun  7 14:10:03 2016 ROUTER_LS (trace) Computed valid origins: {'Router.C': [], 'Router.B': []}
----
<1> `Router.A` sent LSR requests and an RA advertisement to the other routers on the network.
<2> `Router.A` received an LSU from `Router.B`, which has two peers: `Router.A`, and `Router.C` (with a cost of `1`).
<3> `Router.A` received an LSR from both `Router.B` and `Router.C`, and  replied with an LSU.
<4> `Router.A` received an LSU from `Router.C`, which only has one peer: `Router.B` (with a cost of `1`).
<5> After the LSR and LSU messages are exchanged, `Router.A` computed the router topology with the related costs.
====

.Tracing the state of mobile addresses attached to a router
====
In this example, the `ROUTER_MA` logs show the Mobile Address Request (MAR) and Mobile Address Update (MAU) messages sent between three routers:

[options="nowrap"]
----
Tue Jun  7 14:27:20 2016 ROUTER_MA (trace) SENT: MAU(id=Router.A area=0 mobile_seq=1 add=['Cmy_queue', 'Dmy_queue', 'M0my_queue_wp'] del=[]) // <1>
Tue Jun  7 14:27:21 2016 ROUTER_MA (trace) RCVD: MAR(id=Router.C area=0 have_seq=0) // <2>
Tue Jun  7 14:27:21 2016 ROUTER_MA (trace) SENT: MAU(id=Router.A area=0 mobile_seq=1 add=['Cmy_queue', 'Dmy_queue', 'M0my_queue_wp'] del=[])
Tue Jun  7 14:27:22 2016 ROUTER_MA (trace) RCVD: MAR(id=Router.B area=0 have_seq=0) // <3>
Tue Jun  7 14:27:22 2016 ROUTER_MA (trace) SENT: MAU(id=Router.A area=0 mobile_seq=1 add=['Cmy_queue', 'Dmy_queue', 'M0my_queue_wp'] del=[])
Tue Jun  7 14:27:39 2016 ROUTER_MA (trace) RCVD: MAU(id=Router.C area=0 mobile_seq=1 add=['M0my_test'] del=[]) // <4>
Tue Jun  7 14:27:51 2016 ROUTER_MA (trace) RCVD: MAU(id=Router.C area=0 mobile_seq=2 add=[] del=['M0my_test']) // <5>
----
<1> `Router.A` sent MAU messages to the other routers in the network to notify them about the addresses added for `my_queue` and `my_queue_wp`.
<2> `Router.A` received a MAR message in response from `Router.C`.
<3> `Router.A` received another MAR message in response from `Router.B`.
<4> `Router.C` sent a MAU message to notify the other routers that it added and address for `my_test`.
<5> `Router.C` sent another MAU message to notify the other routers that it deleted the address for `my_test` (because the receiver is detached).
====

.Finding information about messages sent and received by a router
====
In this example, the `MESSAGE` logs show that `Router.A` has sent and received some messages related to the Hello protocol, and sent and received some other messages on a link for a mobile address:

[options="nowrap"]
----
Tue Jun  7 14:36:54 2016 MESSAGE (trace) Sending Message{to='amqp:/_topo/0/Router.B/qdrouter' body='\d1\00\00\00\1b\00\00\00\04\a1\02id\a1\08R'} on link qdlink.p9XmBm19uDqx50R
Tue Jun  7 14:36:54 2016 MESSAGE (trace) Received Message{to='amqp:/_topo/0/Router.A/qdrouter' body='\d1\00\00\00\8e\00\00\00
\a1\06ls_se'} on link qdlink.phMsJOq7YaFsGAG
Tue Jun  7 14:36:54 2016 MESSAGE (trace) Received Message{ body='\d1\00\00\00\10\00\00\00\02\a1\08seque'} on link qdlink.FYHqBX+TtwXZHfV
Tue Jun  7 14:36:54 2016 MESSAGE (trace) Sending Message{ body='\d1\00\00\00\10\00\00\00\02\a1\08seque'} on link qdlink.yU1tnPs5KbMlieM
Tue Jun  7 14:36:54 2016 MESSAGE (trace) Sending Message{to='amqp:/_local/qdhello' body='\d1\00\00\00G\00\00\00\08\a1\04seen\d0'} on link qdlink.p9XmBm19uDqx50R
Tue Jun  7 14:36:54 2016 MESSAGE (trace) Sending Message{to='amqp:/_topo/0/Router.C/qdrouter' body='\d1\00\00\00\1b\00\00\00\04\a1\02id\a1\08R'} on link qdlink.p9XmBm19uDqx50R
----
====

.Tracking configuration changes to a router
====
In this example, the `AGENT` logs show that on `Router.A`, `address`, `linkRoute`, and `autoLink` entities were added to the router's configuration file. When the router was started, the `AGENT` module applied these changes, and they are now viewable in the log:

[options="nowrap"]
----
Tue Jun  7 15:07:32 2016 AGENT (debug) Add entity: ConnectorEntity(addr=127.0.0.1, allowRedirect=True, cost=1, host=127.0.0.1, identity=connector/127.0.0.1:5672:BROKER, idleTimeoutSeconds=16, maxFrameSize=65536, name=BROKER, port=5672, role=route-container, stripAnnotations=both, type=org.apache.qpid.dispatch.connector, verifyHostname=True)
Tue Jun  7 15:07:32 2016 AGENT (debug) Add entity: RouterConfigAddressEntity(distribution=closest, identity=router.config.address/0, name=router.config.address/0, prefix=my_address, type=org.apache.qpid.dispatch.router.config.address, waypoint=False)
Tue Jun  7 15:07:32 2016 AGENT (debug) Add entity: RouterConfigAddressEntity(distribution=balanced, identity=router.config.address/1, name=router.config.address/1, prefix=my_queue_wp, type=org.apache.qpid.dispatch.router.config.address, waypoint=True)
Tue Jun  7 15:07:32 2016 AGENT (debug) Add entity: RouterConfigLinkrouteEntity(connection=BROKER, direction=in, distribution=linkBalanced, identity=router.config.linkRoute/0, name=router.config.linkRoute/0, prefix=my_queue, type=org.apache.qpid.dispatch.router.config.linkRoute)
Tue Jun  7 15:07:32 2016 AGENT (debug) Add entity: RouterConfigLinkrouteEntity(connection=BROKER, direction=out, distribution=linkBalanced, identity=router.config.linkRoute/1, name=router.config.linkRoute/1, prefix=my_queue, type=org.apache.qpid.dispatch.router.config.linkRoute)
Tue Jun  7 15:07:32 2016 AGENT (debug) Add entity: RouterConfigAutolinkEntity(address=my_queue_wp, connection=BROKER, direction=in, identity=router.config.autoLink/0, name=router.config.autoLink/0, type=org.apache.qpid.dispatch.router.config.autoLink)
Tue Jun  7 15:07:32 2016 AGENT (debug) Add entity: RouterConfigAutolinkEntity(address=my_queue_wp, connection=BROKER, direction=out, identity=router.config.autoLink/1, name=router.config.autoLink/1, type=org.apache.qpid.dispatch.router.config.autoLink)
----
====

.Troubleshooting policy and vhost access rules
====
In this example, the `POLICY` logs show that this router has no limits on maximum connections, and the default application policy is disabled:

[options="nowrap"]
----
Tue Jun  7 15:07:32 2016 POLICY (info) Policy configured maximumConnections: 0, policyFolder: '', access rules enabled: 'false'
Tue Jun  7 15:07:32 2016 POLICY (info) Policy fallback defaultApplication is disabled
----
====

.Diagnosing errors
====
In this example, the `ERROR` logs show that the router failed to start when an incorrect path was specified for the router's configuration file:

[options="nowrap"]
----
$ qdrouterd --conf my_config
Wed Jun 15 09:53:28 2016 ERROR (error) Python: Exception: Cannot load configuration file my_config: [Errno 2] No such file or directory: 'my_config'
Wed Jun 15 09:53:28 2016 ERROR (error) Traceback (most recent call last):
  File "/usr/lib/qpid-dispatch/python/qpid_dispatch_internal/management/config.py", line 155, in configure_dispatch
    config = Config(filename)
  File "/usr/lib/qpid-dispatch/python/qpid_dispatch_internal/management/config.py", line 41, in __init__
    self.load(filename, raw_json)
  File "/usr/lib/qpid-dispatch/python/qpid_dispatch_internal/management/config.py", line 123, in load
    with open(source) as f:
Exception: Cannot load configuration file my_config: [Errno 2] No such file or directory: 'my_config'

Wed Jun 15 09:53:28 2016 MAIN (critical) Router start-up failed: Python: Exception: Cannot load configuration file my_config: [Errno 2] No such file or directory: 'my_config'
qdrouterd: Python: Exception: Cannot load configuration file my_config: [Errno 2] No such file or directory: 'my_config'
----
====

.Additional resources

* For more information about logging modules, see xref:logging-modules-{context}[].

:leveloffset!:

:leveloffset!:
