////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This assembly is included in the following assemblies:
//
// book.adoc

[id='monitoring-using-web-console'-{context}']
= Monitoring using {ConsoleName}

{ConsoleName} is a web console for monitoring the status and performance of {RouterName} router networks.

//.Prerequisites
Unresolved directive in monitoring-using-web-console.adoc - include::{FragmentDir}/fragment-console-prereq.adoc[]

:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// monitoring-using-web-console.adoc

[id='setting-up-access-web-console'-{context}']
= Setting up access to {ConsoleName}

Before you can access the web console, you must configure a `listener` to accept HTTP connections for the web console and serve the console files.

.Procedure

. On the router from which you want to access the web console, open the `{RouterConfigFile}` configuration file.

. Add a `listener` to serve the console.
+
--
This example creates a `listener` that clients can use to access the web console:

[options="nowrap",subs="+quotes"]
----
listener {
    host: 0.0.0.0
    port: 8672
    role: normal
    http: true
    httpRootDir: /usr/share/qpid-dispatch/console
}
----
`host`:: The IP address (IPv4 or IPv6) or hostname on which the router will listen.

`port`:: The port number or symbolic service name, defined in `/etc/services`, on which the router will listen.

`role`:: The role of the connection. Specify `normal` to indicate that this connection is used for client traffic.

`http`:: Set this attribute to `true` to specify that this `listener` should accept HTTP connections instead of plain AMQP connections.

`httpRootDir`:: Specify the absolute path to the directory that contains the web console HTML files. The default directory is the stand-alone console installation directory, usually `/usr/share/qpid-dispatch/console`.
--

. If you want to secure access to the console, secure the `listener`.
+
--
For more information, see xref:securing-incoming-client-connections-{context}[]. This example adds basic user name and password authentication using SASL PLAIN:

[options="nowrap",subs="+quotes"]
----
listener {
    host: 0.0.0.0
    port: 8672
    role: normal
    http: true
    httpRootDir: /usr/share/qpid-dispatch/console
    authenticatePeer: yes
    saslMechanisms: PLAIN
}
----
--

. If you want to set up access to the web console from any other router in the router network, repeat this procedure for each router.

:leveloffset!:

:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// monitoring-using-web-console.adoc

[id='accessing-web-console'-{context}']
= Accessing {ConsoleName}

You can access the web console from a web browser.

.Procedure

. In a web browser, navigate to the web console URL.
+
--
The web console URL is the _<host>_:__<port>__ from the `listener` that you created to serve the web console. For example: `localhost:8672`.

The {ConsoleName} opens. If you set up user name and password authentication, the *Connect* tab is displayed.
--

. If necessary, log in to the web console.
+
--
If you set up user name and password authentication, enter your user name and password to access the web console.

The syntax for the user name is <__user__>@<__domain__>. For example: `admin@my-domain`.
--

:leveloffset!:

:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// This module is included in the following assemblies:
//
// monitoring-using-web-console.adoc

[id='monitoring-router-network-web-console'-{context}']
= Monitoring the router network using {ConsoleName}

The web console provides several sections that you can use to monitor the router network.

[cols="25,75"]
|===
| This section... | Provides...

| Overview
a|
Aggregated information about the router network. This information includes the following:

* Dashboard (shows router network statistics)
* Routers
* Addresses
* Links
* Connections
* Logs

| Visualizations
a|
Graphical view of the router network. You can see the following types of visualizations:

`Topology`:: Topology of the router network, including routers, clients, and brokers. This visualization also shows how messages are flowing through the network.
`Message flow`:: A chord diagram showing the real-time message flow by address.

| Details
| Detailed configuration information about each AMQP management entity, for each router in the router network. You can view and change the configuration of any of the routers in the network.

|===

:leveloffset!:
