////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module is included in the following assemblies:
//
// securing-network-connections.adoc

[id='securing-incoming-client-connections-{context}']
= Securing incoming client connections

You can use SSL/TLS and SASL to provide the appropriate level of security for client traffic into the router network. You can use the following methods to secure incoming connections to a router from AMQP clients, external containers, or edge routers:

* xref:enabling-ssl-tls-encryption-{context}[Enable SSL/TLS encryption]
* xref:enabling-ssl-tls-client-authentication-{context}[Enable SSL/TLS client authentication]
* xref:enabling-username-password-authentication-{context}[Enable user name and password authentication]
* xref:integrating-with-kerberos-{context}[Integrate with Kerberos]

// Enabling SSL/TLS encryption
:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module is included in the following assemblies:
//
// securing-incoming-client-connections.adoc

[id='enabling-ssl-tls-encryption-{context}']
= Enabling SSL/TLS encryption

You can use SSL/TLS to encrypt an incoming connection from a client.

.Prerequisites

* An X.509 Certificate Authority (CA) must exist for the client connections.

* A security certificate must be generated and signed by the CA.

.Procedure

include::partial$fragment-router-open-config-file-step.adoc[]

. If the router does not contain an `sslProfile` that defines the private keys and certificates for client connections, then add one.
+
--
This `sslProfile` contains the locations of the private key and certificates that the router should use to encrypt connections from clients.

[options="nowrap",subs="+quotes"]
----
sslProfile {
    name: service-tls
    certFile: /etc/pki/tls/certs/tls.crt
    caCertFile: /etc/pki/tls/certs/ca.crt
    privateKeyFile: /etc/pki/tls/private/tls.key
    password: file:/etc/pki/tls/private/password.txt
    ...
}
----
`name`:: A unique name that you can use to refer to this `sslProfile`.

`certFile`:: The absolute path to the file containing the public certificate for this router.

`caCertFile`:: The absolute path to the CA certificate that the router uses to authenticate incoming clients.

`privateKeyFile`:: The absolute path to the file containing the private key for this router's public certificate.
+
[NOTE]
====
Ensure that the `qdrouterd` or root user can access the private key. For example:

[options="nowrap",subs="+quotes"]
----
chmod 0600 /etc/pki/tls/private/tls.key
chown qdrouterd /etc/pki/tls/private/tls.key
----
====

//`password`
include::partial$fragment-password-description.adoc[]
--

. Configure the `listener` for this connection to use SSL/TLS to encrypt the connection.
+
--
This example configures a `normal` listener to encrypt connections from clients.

[options="nowrap",subs="+quotes"]
----
listener {
    host: 0.0.0.0
    port: 5672
    role: normal
    sslProfile: inter_router_tls
    requireSsl: yes
    ...
}
----
`sslProfile`:: The name of the `sslProfile` that defines the SSL/TLS private keys and certificates for client connections.

`requireSsl`:: Specify `true` to encrypt the connection with SSL/TLS.
--

:leveloffset!:

// Enabling SSL/TLS client authentication
:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module is included in the following assemblies:
//
// securing-incoming-client-connections.adoc

[id='enabling-ssl-tls-client-authentication-{context}']
= Enabling SSL/TLS client authentication

In addition to SSL/TLS encryption, you can also use SSL/TLS to authenticate an incoming connection from a client. With this method, a clients must present its own X.509 certificate to the router, which the router uses to verify the client's identity.

.Prerequisites

* SSL/TLS encryption must be configured.
+
For more information, see xref:enabling-ssl-tls-encryption-{context}[].

* The client must have an X.509 certificate that it can use to authenticate to the router.

.Procedure

include::partial$fragment-router-open-config-file-step.adoc[]

. Configure the `listener` for this connection to use SSL/TLS to authenticate the client.
+
--
This example adds SSL/TLS authentication to a `normal` listener to authenticate incoming connections from a client. The client will only be able to connect to the router by presenting its own X.509 certificate to the router, which the router will use to verify the client's identity.

[options="nowrap",subs="+quotes"]
----
listener {
    host: 0.0.0.0
    port: 5672
    role: normal
    sslProfile: service-tls
    requireSsl: yes
    authenticatePeer: yes
    saslMechanisms: EXTERNAL
    ...
}
----
`authenticatePeer`:: Specify `yes` to authenticate the client's identity.

`saslMechanisms`:: Specify `EXTERNAL` to enable X.509 client certificate authentication.
--

:leveloffset!:

// Enabling username/password authentication
:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module is included in the following assemblies:
//
// securing-incoming-client-connections.adoc

[id='enabling-username-password-authentication-{context}']
= Enabling user name and password authentication

You can use the SASL PLAIN mechanism to authenticate incoming client connections against a set of user names and passwords. You can use this method by itself, or you can combine it with SSL/TLS encryption.

.Prerequisites

* The `cyrus-sasl-plain` plugin is installed.
+
Cyrus SASL uses plugins to support specific SASL mechanisms. Before you can use a particular SASL mechanism, the relevant plugin must be installed.
+
--
// Note about searching for an installing SASL plugins.
include::partial$fragment-router-sasl-para.adoc[]
--

.Procedure

. If necessary, add the user names and passwords to the SASL database.
+
--
This example adds a new user (\user1@example.com) to the SASL database (qdrouterd.sasldb):

[options="nowrap",subs="+quotes"]
----
$ sudo saslpasswd2 -c -f qdrouterd.sasldb -u example.com user1
----

[NOTE]
====
The full user name is the user name you entered plus the domain name (`__<user-name>__`@`__<domain-name>__`). Providing a domain name is not required when you add a user to the database, but if you do not provide one, a default domain will be added automatically (the hostname of the machine on which the tool is running).
====
--

. Ensure that the `qdrouterd` process can read the SASL database.
+
--
If the `qdrouterd` process runs as an unprivileged user, you might need to adjust the permissions or ownership of the SASL database so that the router can read it.

This example makes the qdrouterd user the owner of the SASL database:

[options="nowrap"]
----
$ sudo chown qdrouterd /var/lib/qdrouterd/qdrouterd.sasldb
----
--

. Open the `/etc/sasl2/qdrouterd.conf` configuration file.
+
--
This example shows a `/etc/sasl2/qdrouterd.conf` configuration file:

[options="nowrap",subs="+quotes"]
----
pwcheck_method: auxprop
auxprop_plugin: sasldb
sasldb_path: qdrouterd.sasldb
mech_list: ANONYMOUS DIGEST-MD5 EXTERNAL PLAIN GSSAPI
----
--

. Verify that the `mech_list` attribute contains the `PLAIN` mechanism.

. Open the `{RouterConfigFile}` configuration file.

. In the `router` section, specify the path to the SASL configuration file.
+
--
[options="nowrap",subs="+quotes"]
----
router {
    mode: interior
    id: Router.A
    saslConfigDir: /etc/sasl2/
}
----
`saslConfigDir`:: The absolute path to the SASL configuration file that contains the path to the SASL database that stores the user names and passwords.
--

. Configure the `listener` for this connection to authenticate clients using SASL PLAIN.
+
--
This example configures basic user name and password authentication for a `listener`. In this case, no SSL/TLS encryption is being used.

[options="nowrap",subs="+quotes"]
----
listener {
    host: 0.0.0.0
    port: 5672
    authenticatePeer: yes
    saslMechanisms: PLAIN
    }
----
--

:leveloffset!:

// Integrating with Kerberos
:leveloffset: +1

////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

// Module is included in the following assemblies:
//
// securing-incoming-client-connections.adoc

[id='integrating-with-kerberos-{context}']
= Integrating with Kerberos

If you have implemented Kerberos in your environment, you can use it with the `GSSAPI` SASL mechanism to authenticate incoming connections.

.Prerequisites

* A Kerberos infrastructure must be deployed in your environment.

* In the Kerberos environment, a service principal of `amqp/<hostname>@<realm>` must be configured.
+
This is the service principal that {RouterName} uses.

* The `cyrus-sasl-gssapi` package must be installed on each client and the router host machine.

.Procedure

. On the router's host machine, open the `/etc/sasl2/qdrouterd.conf` configuration file.
+
--
This example shows a `/etc/sasl2/qdrouterd.conf` configuration file:

[options="nowrap"]
----
pwcheck_method: auxprop
auxprop_plugin: sasldb
sasldb_path: qdrouterd.sasldb
keytab: /etc/krb5.keytab
mech_list: ANONYMOUS DIGEST-MD5 EXTERNAL PLAIN GSSAPI
----
--

. Verify the following:
+
--
* The `mech_list` attribute contains the `GSSAPI` mechanism.
* The `keytab` attribute points to the location of the keytab file.
--

. Open the `{RouterConfigFile}` configuration file.

. In the `router` section, specify the path to the SASL configuration file.
+
--
[options="nowrap",subs="+quotes"]
----
router {
    mode: interior
    id: Router.A
    saslConfigDir: /etc/sasl2/
}
----
`saslConfigDir`:: The absolute path to the SASL configuration file that contains the path to the SASL database.
--

. For each incoming connection using Kerberos for authentication, set the `listener` to use the `GSSAPI` mechanism.
+
--
----
listener {
    host: 0.0.0.0
    port: 5672
    authenticatePeer: yes
    saslMechanisms: GSSAPI
    }
----
--

:leveloffset!:
