////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License
////

= Packaging

== rpm

The `packit` tool edits the `packaging/skupper-router.srpm` file.
There is probably some rhyme and reason to what it does, but so far it is beyond the ken of this paragraph's author.
When building, beware of committing the changes it introduces.

https://copr.fedorainfracloud.org/[COPR] builds can be initiated with `packit` CLI, or using the following script in COPR Web UI.

=== Packit CLI

NOTE: If the Packit CLI procedure fails with ERROR, try the COPR Web UI

Refer to docs for [packit build in-copr](https://packit.dev/docs/cli/build/copr/) command.

1. Create `~/.config/copr` as instructed.
2. Authenticate with `fkinit` [according to instructions](https://fedoraproject.org/wiki/Infrastructure/Kerberos#How_to_use_kerberos_auth_with_Fedora_Infrastructure)

Now, initiate the build

[source, shell script]
----
packit build in-copr --owner $USER --project skupper-router
----

=== COPR Web UI

* Select the `Custom` source type.
* Paste the script below in the _Script_ field.
* Specify `git packit` in the _Build dependencies_ field.
* Enter `skupper-router/prepare_sources_result` into _Result directory_ field.

[source,shell script]
----
#!/bin/bash
set -Exeuo pipefail

git clone --branch main https://github.com/skupperproject/skupper-router.git
cd skupper-router
packit prepare-sources
----

== Packit

Install Packit CLI tool from https://packit.dev/docs/cli/#installation

[source,shell script]
----
packit srpm
rpmbuild --rebuild <path to generated srpm>
----
